theme: "just-the-docs"

# Sidebar navigation
just_the_docs:
  # Enable the sidebar with navigation
  show_sidebar: true
  # Site title and description
  title: "Base64 File Plugin Documentation"
  description: "Documentation for the Base64 File plugin for IntelliJ IDEA."
  logo: "/assets/logo.png"
  # Set up sidebar links
  navigation_structure:
    - title: "Introduction"
      url: "/docs/introduction/"
    - title: "Installation"
      url: "/docs/installation/"
    - title: "Usage"
      url: "/docs/usage/"
