title: Base64 File Plugin
description: Documentation for Base64 File Plugin for IntellijIDEA
url: "http://base64file.com" # Your website URL
author:
  name: Vaclav Tolar

logo: /assets/images/logo.svg


theme: minimal-mistakes-jekyll

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

include: [ "_pages", "_docs" ]

collections:
  docs:
    output: true
    sort_by: weight
    permalink: /docs/:title/
  use_cases:
    output: true
    sort_by: weight
    permalink: /use_cases/:title/


defaults:
  - scope:
      path: ""
      type: docs
    values:
      toc: true
      toc_label: "On this page"
      toc_sticky: true
      sidebar:
        nav: "doc-nav"
  - scope:
      path: ""
      type: use_cases
    values:
      toc: false
      sidebar:
        nav: "use-cases-nav"





