title: Base64 File Plugin
description: Documentation for Base64 File Plugin for IntellijIDEA
url: "http://base64file.com" # Your website URL
#baseurl: "/base64-file-plugin-doc"
baseurl: ""  # Set this to an empty string for custom domains
author:
  name: Vaclav Tolar

logo: /assets/images/logo.svg


#theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes@4.26.2

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

include: [ "_pages", "_docs" ]

collections:
  docs:
    output: true
    sort_by: weight
    permalink: /docs/:title/
  use_cases:
    output: true
    sort_by: weight
    permalink: /use_cases/:title/


defaults:
  - scope:
      path: ""
      type: docs
    values:
      toc: true
      toc_label: "On this page"
      toc_sticky: true
      sidebar:
        nav: "doc-nav"
  - scope:
      path: ""
      type: use_cases
    values:
      toc: false
      sidebar:
        nav: "use-cases-nav"





